#!/usr/bin/env python
"""Temporary script to update core/providers.py with new provider presets."""
from pathlib import Path

target = Path(__file__).parent / "core" / "providers.py"
lines = target.read_text(encoding="utf-8").splitlines(keepends=False)

# Find PROVIDERS start and class ProviderRegistry start
providers_start = next(i for i, line in enumerate(lines) if line.strip() == 'PROVIDERS = {')
registry_start = next(i for i, line in enumerate(lines) if line.strip().startswith('class ProviderRegistry:'))

# Build new PROVIDERS block
new_providers = '''PROVIDERS = {
    "anthropic": ProviderConfig(
        name="anthropic",
        display_name="Anthropic (官方)",
        default_base_url="https://api.anthropic.com",
        default_model="claude-sonnet-4",
        supported_models=[
            "sonnet",
            "sonnet[1m]",
            "opus[1m]",
         "opus",
            "opusplan",
        "haiku",
            "claude-opus-4-7",
            "claude-opus-4-7[1m]",
        "claude-sonnet-4-6",
            "claude-sonnet-4-6[1m]",
            "claude-haiku-4-5",
        "claude-opus-4",
      "claude-sonnet-4",
         "claude-haiku-4",
            "claude-sonnet-4-20250514",
            "claude-opus-4-20250514",
        ],
        reasoning_efforts=CLAUDE_CODE_EFFORTS,
        requires_auth=True,
        auth_header="x-api-key",
        codex_supported=False,
    ),
    "openai": ProviderConfig(
        name="openai",
        display_name="OpenAI (官方)",
        default_base_url="https://api.openai.com/v1",
        default_model="gpt-5.5",
        supported_models=[
            "gpt-5.5",
            "gpt-5.4",
            "gpt-5.3-codex",
            "gpt-5.2",
            "gpt-4o",
        ],
        reasoning_efforts=CODEX_REASONING_EFFORTS,
        requires_auth=True,
        auth_header="Authorization",
        wire_api="responses",
        requires_openai_auth=False,
        codex_env_key="OPENAI_API_KEY",
    claude_supported=False,
      notes="OpenAI 官方 API，Codex 使用 Responses wire API。",
    ),
    "deepseek": ProviderConfig(
        name="deepseek",
        display_name="DeepSeek",
        default_base_url="https://api.deepseek.com",
        claude_base_url="https://api.deepseek.com/anthropic",
        default_model="deepseek-v4-flash",
        supported_models=[
            "deepseek-v4-flash",
            "deepseek-v4-pro",
         "deepseek-chat",
            "deepseek-reasoner",
        ],
        reasoning_efforts=CLAUDE_CODE_EFFORTS,
        requires_auth=True,
        auth_header="Authorization",
        wire_api="responses",
        requires_openai_auth=False,
      codex_env_key="DEEPSEEK_API_KEY",
        notes="DeepSeek Codex 使用 Responses wire API；Claude Code 使用 Anthropic 兼容端点。",
    ),
    "kimi": ProviderConfig(
        name="kimi",
        display_name="Kimi (Moonshot)",
        default_base_url="https://api.moonshot.ai/v1",
        claude_base_url="https://api.moonshot.ai/v1",
      default_model="kimi-k2.6",
        supported_models=[
            "kimi-k2.6",
       "kimi-k2.5",
            "kimi-k2",
            "kimi-k2-thinking",
            "kimi-k2-thinking-turbo",
            "moonshot-v1-8k",
          "moonshot-v1-32k",
         "moonshot-v1-128k",
        ],
        reasoning_efforts=[],
        requires_auth=True,
        auth_header="Authorization",
        wire_api="responses",
        requires_openai_auth=False,
      codex_env_key="MOONSHOT_API_KEY",
        notes="Kimi Codex 使用 Responses wire API；Claude Code 也支持 Kimi OpenAI 兼容端点。中国平台密钥可用 https://api.moonshot.cn/v1。",
    ),
    "minimax": ProviderConfig(
      name="minimax",
        display_name="MiniMax",
        default_base_url="https://api.minimax.chat/v1",
      claude_base_url="https://api.minimax.chat/v1",
        default_model="MiniMax-Text-01",
        supported_models=[
            "MiniMax-Text-01",
            "abab6.5s-chat",
          "abab6.5g-chat",
            "abab6.5t-chat",
            "abab5.5s-chat",
            "abab5.5-chat",
        ],
        reasoning_efforts=[],
        requires_auth=True,
        auth_header="Authorization",
        wire_api="responses",
        requires_openai_auth=False,
        codex_env_key="MINIMAX_API_KEY",
        notes="MiniMax Codex 使用 Responses wire API；Claude Code 也支持 MiniMax OpenAI 兼容端点。",
    ),
    "qwen": ProviderConfig(
        name="qwen",
        display_name="Qwen (通义千问)",
        default_base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",
        claude_base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",
        default_model="qwen-max",
        supported_models=[
            "qwen-max",
            "qwen-plus",
            "qwen-turbo",
          "qwen-coder-turbo",
            "qwen2.5-coder-32b-instruct",
        ],
        reasoning_efforts=[],
        requires_auth=True,
      auth_header="Authorization",
     wire_api="responses",
        requires_openai_auth=False,
        codex_env_key="DASHSCOPE_API_KEY",
        notes="Qwen DashScope 兼容模式，Codex 使用 Responses wire API；Claude Code 也支持 Qwen OpenAI 兼容端点。",
    ),
    "glm": ProviderConfig(
        name="glm",
        display_name="GLM (Zhipu/Z.ai)",
        default_base_url="https://open.bigmodel.cn/api/coding/paas/v4",
        claude_base_url="",
        default_model="GLM-5.1",
      supported_models=[
         "GLM-5.1",
            "GLM-5",
            "GLM-5-Turbo",
         "GLM-4.7",
            "GLM-4.7-Flash",
            "GLM-4.6",
            "GLM-4.5",
            "GLM-4.5-Air",
        "GLM-4.5-air",
        ],
        reasoning_efforts=[],
        requires_auth=True,
        auth_header="Authorization",
        wire_api="responses",
        requires_openai_auth=False,
        codex_env_key="ZHIPUAI_API_KEY",
      claude_env={
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "GLM-5.1",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "GLM-5.1",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "GLM-4.5-air",
      },
        claude_supported=False,
        notes="GLM Coding Plan 配置 Responses wire API，仅支持 Codex。",
    ),
    "custom": ProviderConfig(
        name="custom",
        display_name="Custom",
        default_base_url="",
        default_model="",
        supported_models=[],
        reasoning_efforts=CODEX_REASONING_EFFORTS,
        requires_auth=True,
        auth_header="Authorization",
        wire_api="responses",
        requires_openai_auth=False,
    ),
}
'''

# Rebuild file
new_lines = lines[:providers_start] + new_providers.splitlines() + ['', ''] + lines[registry_start:]
target.write_text('\n'.join(new_lines) + '\n', encoding='utf-8')
print(f"Updated {target}")
