"""
生成 API 错误自动恢复的 Hook 脚本
用于检测各种 API 错误并采取相应的恢复策略
"""


def generate_error_recovery_script(settings_path: str) -> str:
    """生成错误恢复 Hook 脚本（增强版）"""

    script = f'''# API Error Recovery Hook Script (Enhanced)
# 自动检测和处理各种 API 错误
# Generated by API切换器

$ErrorActionPreference = "Stop"

# 日志函数
function Write-Log {{
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logMessage = "$timestamp [$Level] $Message"
    Write-Error $logMessage
}}

# 错误类型枚举
$ErrorTypes = @{{
    CONTENT_LENGTH_EXCEEDED = "content_length_exceeded"
    RATE_LIMIT_EXCEEDED = "rate_limit_exceeded"
    AUTHENTICATION_ERROR = "authentication_error"
    PERMISSION_DENIED = "permission_denied"
    QUOTA_EXCEEDED = "quota_exceeded"
    MODEL_OVERLOADED = "model_overloaded"
    TIMEOUT_ERROR = "timeout_error"
    NETWORK_ERROR = "network_error"
    SERVER_ERROR = "server_error"
    INVALID_REQUEST = "invalid_request"
    UNKNOWN = "unknown"
}}

# 恢复策略枚举
$RecoveryStrategies = @{{
    COMPACT_AND_CONTINUE = "compact_and_continue"
    RETRY_WITH_BACKOFF = "retry_with_backoff"
    WAIT_AND_RETRY = "wait_and_retry"
    NOTIFY_USER = "notify_user"
    ABORT = "abort"
    NONE = "none"
}}

# 错误分类函数
function Get-ErrorType {{
    param([string]$ErrorCode, [string]$ErrorMessage, [int]$HttpStatus)

    $combined = "$ErrorCode $ErrorMessage".ToLower()

    # 内容超长
    $contentPatterns = @(
        "content_length_exceeds_threshold",
        "context.*length.*exceeded",
        "maximum context length",
        "对话内容超出长度限制",
        "内容太长",
        "tokens?.*exceed",
        "上下文.*超出"
    )
    foreach ($pattern in $contentPatterns) {{
        if ($combined -match $pattern) {{
            return $ErrorTypes.CONTENT_LENGTH_EXCEEDED
        }}
    }}

    # 速率限制
    $ratePatterns = @(
        "rate.*limit.*exceeded",
        "too.*many.*requests",
        "请求过于频繁",
        "速率限制"
    )
    if ($HttpStatus -eq 429) {{
        return $ErrorTypes.RATE_LIMIT_EXCEEDED
    }}
    foreach ($pattern in $ratePatterns) {{
        if ($combined -match $pattern) {{
            return $ErrorTypes.RATE_LIMIT_EXCEEDED
        }}
    }}

    # 认证错误
    if ($HttpStatus -eq 401 -or $combined -match "authentication.*failed|invalid.*api.*key|unauthorized|认证失败") {{
        return $ErrorTypes.AUTHENTICATION_ERROR
    }}

    # 权限错误
    if ($HttpStatus -eq 403 -or $combined -match "permission.*denied|access.*denied|forbidden|权限不足") {{
        return $ErrorTypes.PERMISSION_DENIED
    }}

    # 配额超限
    if ($combined -match "quota.*exceeded|insufficient.*quota|配额.*超出|余额不足") {{
        return $ErrorTypes.QUOTA_EXCEEDED
    }}

    # 模型过载
    if ($HttpStatus -eq 503 -or $combined -match "model.*overloaded|server.*overloaded|capacity.*exceeded|服务器.*繁忙") {{
        return $ErrorTypes.MODEL_OVERLOADED
    }}

    # 超时
    if ($HttpStatus -eq 504 -or $combined -match "timeout|timed.*out|超时") {{
        return $ErrorTypes.TIMEOUT_ERROR
    }}

    # 网络错误
    if ($combined -match "network.*error|connection.*failed|connection.*refused|网络.*错误|连接.*失败") {{
        return $ErrorTypes.NETWORK_ERROR
    }}

    # 服务器错误
    if (($HttpStatus -ge 500 -and $HttpStatus -lt 600) -or $combined -match "internal.*server.*error|server.*error|服务器.*错误") {{
        return $ErrorTypes.SERVER_ERROR
    }}

    # 无效请求
    if ($HttpStatus -ge 400 -and $HttpStatus -lt 500) {{
        return $ErrorTypes.INVALID_REQUEST
    }}

    return $ErrorTypes.UNKNOWN
}}

# 获取恢复策略
function Get-RecoveryStrategy {{
    param([string]$ErrorType)

    $strategyMap = @{{
        $ErrorTypes.CONTENT_LENGTH_EXCEEDED = $RecoveryStrategies.COMPACT_AND_CONTINUE
        $ErrorTypes.RATE_LIMIT_EXCEEDED = $RecoveryStrategies.WAIT_AND_RETRY
        $ErrorTypes.MODEL_OVERLOADED = $RecoveryStrategies.RETRY_WITH_BACKOFF
        $ErrorTypes.TIMEOUT_ERROR = $RecoveryStrategies.RETRY_WITH_BACKOFF
        $ErrorTypes.NETWORK_ERROR = $RecoveryStrategies.RETRY_WITH_BACKOFF
        $ErrorTypes.SERVER_ERROR = $RecoveryStrategies.RETRY_WITH_BACKOFF
        $ErrorTypes.AUTHENTICATION_ERROR = $RecoveryStrategies.NOTIFY_USER
        $ErrorTypes.PERMISSION_DENIED = $RecoveryStrategies.NOTIFY_USER
        $ErrorTypes.QUOTA_EXCEEDED = $RecoveryStrategies.NOTIFY_USER
        $ErrorTypes.INVALID_REQUEST = $RecoveryStrategies.ABORT
        $ErrorTypes.UNKNOWN = $RecoveryStrategies.NONE
    }}

    if ($strategyMap.ContainsKey($ErrorType)) {{
        return $strategyMap[$ErrorType]
    }}
    return $RecoveryStrategies.NONE
}}

# 提取重试等待时间
function Get-RetryAfter {{
    param([string]$ErrorMessage)

    # 匹配 "请在 X 秒后重试" 或 "retry after X seconds"
    if ($ErrorMessage -match '(\\d+)\\s*秒后.*重试') {{
        return [int]$Matches[1]
    }}
    if ($ErrorMessage -match 'retry.*?(\\d+)\\s*second') {{
        return [int]$Matches[1]
    }}
    if ($ErrorMessage -match 'wait.*?(\\d+)\\s*second') {{
        return [int]$Matches[1]
    }}

    return $null
}}

try {{
    # 读取配置
    $settingsPath = "{settings_path}"
    if (-not (Test-Path $settingsPath)) {{
        Write-Log "Settings file not found: $settingsPath" "WARN"
        exit 0
    }}

    try {{
        $settings = Get-Content $settingsPath -Raw -ErrorAction Stop | ConvertFrom-Json -ErrorAction Stop
    }} catch {{
        Write-Log "Failed to parse settings JSON: $_" "ERROR"
        exit 0
    }}

    # 检查是否启用错误恢复
    if (-not $settings.error_recovery_enabled) {{
        exit 0
    }}

    # 读取 stdin (Hook 输入)
    $stdinLines = @()
    $timeout = 5
    $startTime = Get-Date
    while ($null -ne ($line = [Console]::ReadLine())) {{
        $stdinLines += $line
        if (((Get-Date) - $startTime).TotalSeconds -gt $timeout) {{
            Write-Log "Stdin read timeout" "WARN"
            break
        }}
    }}
    $stdin = $stdinLines -join "`n"

    if ([string]::IsNullOrWhiteSpace($stdin)) {{
        exit 0
    }}

    # 解析输入 JSON
    try {{
        $input = $stdin | ConvertFrom-Json -ErrorAction Stop
    }} catch {{
        Write-Log "Failed to parse input JSON: $_" "ERROR"
        exit 0
    }}

    # 提取错误信息
    $errorCode = $input.error_code
    $errorMessage = $input.error_message
    $httpStatus = $input.status
    $sessionId = $input.session_id

    # 尝试从嵌套的 error 对象中提取
    if ($input.error) {{
        if ($input.error.code) {{ $errorCode = $input.error.code }}
        if ($input.error.message) {{ $errorMessage = $input.error.message }}
        if ($input.error.status) {{ $httpStatus = $input.error.status }}
    }}

    if ([string]::IsNullOrWhiteSpace($errorCode) -and [string]::IsNullOrWhiteSpace($errorMessage)) {{
        exit 0  # 不是错误，正常退出
    }}

    Write-Log "Detected API error: [$errorCode] $errorMessage (HTTP $httpStatus)" "INFO"

    # 分类错误类型
    $errorType = Get-ErrorType -ErrorCode $errorCode -ErrorMessage $errorMessage -HttpStatus $httpStatus
    Write-Log "Error type: $errorType" "INFO"

    # 获取恢复策略
    $recoveryStrategy = Get-RecoveryStrategy -ErrorType $errorType
    Write-Log "Recovery strategy: $recoveryStrategy" "INFO"

    # 如果没有恢复策略，退出
    if ($recoveryStrategy -eq $RecoveryStrategies.NONE -or $recoveryStrategy -eq $RecoveryStrategies.ABORT) {{
        Write-Log "No recovery strategy available for this error type" "INFO"
        exit 0
    }}

    # 检查恢复次数限制
    $stateDir = Split-Path $settingsPath
    $statePath = Join-Path $stateDir "error_recovery_state.json"
    $state = @{{}}
    if (Test-Path $statePath) {{
        try {{
            $stateContent = Get-Content $statePath -Raw -ErrorAction Stop
            $state = $stateContent | ConvertFrom-Json -ErrorAction Stop -AsHashtable
        }} catch {{
            $state = @{{}}
        }}
    }}

    $recoveryKey = "$sessionId-$errorType"
    $recoveryCount = if ($state.ContainsKey($recoveryKey)) {{ $state[$recoveryKey] }} else {{ 0 }}
    $maxRecoveries = if ($settings.max_error_recoveries) {{ $settings.max_error_recoveries }} else {{ 3 }}

    if ($recoveryCount -ge $maxRecoveries) {{
        Write-Log "Max recovery attempts reached ($maxRecoveries) for $errorType" "WARN"

        # 记录日志
        $recoveryLogPath = Join-Path $stateDir "error_recovery_log.jsonl"
        $logEntry = @{{
            timestamp = (Get-Date -Format "o")
            session_id = $sessionId
            error_type = $errorType
            error_code = $errorCode
            error_message = $errorMessage
            http_status = $httpStatus
            recovery_strategy = $recoveryStrategy
            action = "max_recoveries_reached"
            recovery_count = $recoveryCount
        }} | ConvertTo-Json -Compress
        Add-Content -Path $recoveryLogPath -Value $logEntry -ErrorAction SilentlyContinue

        exit 0
    }}

    # 更新恢复次数
    $recoveryCount++
    $state[$recoveryKey] = $recoveryCount
    try {{
        $tempPath = "$statePath.tmp"
        $state | ConvertTo-Json | Set-Content $tempPath -ErrorAction Stop
        Move-Item -Path $tempPath -Destination $statePath -Force -ErrorAction Stop
    }} catch {{
        Write-Log "Failed to save recovery state: $_" "ERROR"
    }}

    # 记录恢复尝试
    $recoveryLogPath = Join-Path $stateDir "error_recovery_log.jsonl"
    $logEntry = @{{
        timestamp = (Get-Date -Format "o")
        session_id = $sessionId
        error_type = $errorType
        error_code = $errorCode
        error_message = $errorMessage
        http_status = $httpStatus
        recovery_strategy = $recoveryStrategy
        action = "attempting_recovery"
        recovery_count = $recoveryCount
    }} | ConvertTo-Json -Compress
    Add-Content -Path $recoveryLogPath -Value $logEntry -ErrorAction SilentlyContinue

    # 根据恢复策略生成响应
    $output = $null

    if ($recoveryStrategy -eq $RecoveryStrategies.COMPACT_AND_CONTINUE) {{
        # 压缩并继续
        $output = @{{
            decision = "recover"
            commands = @(
                @{{
                    type = "slash_command"
                    command = "compact"
                }},
                @{{
                    type = "user_message"
                    message = "继续"
                }}
            )
            suppressOutput = $true
            userMessage = "对话内容过长，正在自动压缩并继续..."
        }} | ConvertTo-Json -Depth 10

    }} elseif ($recoveryStrategy -eq $RecoveryStrategies.WAIT_AND_RETRY) {{
        # 等待后重试
        $retryAfter = Get-RetryAfter -ErrorMessage $errorMessage
        if (-not $retryAfter) {{ $retryAfter = 60 }}  # 默认等待 60 秒

        $output = @{{
            decision = "recover"
            commands = @(
                @{{
                    type = "wait"
                    seconds = $retryAfter
                }},
                @{{
                    type = "user_message"
                    message = "继续"
                }}
            )
            suppressOutput = $true
            userMessage = "请求过于频繁，等待 $retryAfter 秒后重试..."
        }} | ConvertTo-Json -Depth 10

    }} elseif ($recoveryStrategy -eq $RecoveryStrategies.RETRY_WITH_BACKOFF) {{
        # 指数退避重试
        $backoffSeconds = [Math]::Min(5 * [Math]::Pow(2, $recoveryCount - 1), 60)  # 5, 10, 20, 40, 60

        $output = @{{
            decision = "recover"
            commands = @(
                @{{
                    type = "wait"
                    seconds = $backoffSeconds
                }},
                @{{
                    type = "user_message"
                    message = "继续"
                }}
            )
            suppressOutput = $true
            userMessage = "服务暂时不可用，等待 $backoffSeconds 秒后重试..."
        }} | ConvertTo-Json -Depth 10

    }} elseif ($recoveryStrategy -eq $RecoveryStrategies.NOTIFY_USER) {{
        # 通知用户
        $userMsg = switch ($errorType) {{
            $ErrorTypes.AUTHENTICATION_ERROR {{ "认证失败，请检查 API 密钥" }}
            $ErrorTypes.PERMISSION_DENIED {{ "权限不足，请检查账户权限" }}
            $ErrorTypes.QUOTA_EXCEEDED {{ "配额已用完，请充值或等待配额重置" }}
            default {{ "发生错误: $errorMessage" }}
        }}

        $output = @{{
            decision = "notify"
            userMessage = $userMsg
            suppressOutput = $false
        }} | ConvertTo-Json -Depth 10
    }}

    if ($output) {{
        Write-Output $output
        Write-Log "Recovery initiated: $recoveryStrategy (attempt $recoveryCount/$maxRecoveries)" "INFO"
    }}

}} catch {{
    Write-Log "Unexpected error in recovery hook: $_" "ERROR"
    exit 0
}}

exit 0
'''

    return script


def generate_codex_error_recovery_script(settings_path: str) -> str:
    """生成 Codex CLI 的错误恢复脚本（增强版）"""

    script = f'''# Codex CLI Error Recovery Hook Script (Enhanced)
# 自动检测和处理各种 API 错误

$ErrorActionPreference = "Stop"

function Write-Log {{
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logMessage = "$timestamp [$Level] $Message"
    Write-Error $logMessage
}}

# 错误分类函数（简化版）
function Get-ErrorType {{
    param([string]$ErrorCode, [string]$ErrorMessage)
    $combined = "$ErrorCode $ErrorMessage".ToLower()

    if ($combined -match "content.*length|context.*length|内容.*长|上下文.*超") {{
        return "content_length"
    }}
    if ($combined -match "rate.*limit|too.*many|频繁|速率") {{
        return "rate_limit"
    }}
    if ($combined -match "timeout|超时") {{
        return "timeout"
    }}
    if ($combined -match "overload|繁忙|503") {{
        return "overload"
    }}
    if ($combined -match "auth|401|认证") {{
        return "auth"
    }}
    if ($combined -match "quota|配额|余额") {{
        return "quota"
    }}

    return "unknown"
}}

try {{
    $settingsPath = "{settings_path}"
    if (-not (Test-Path $settingsPath)) {{
        exit 0
    }}

    $settings = Get-Content $settingsPath -Raw | ConvertFrom-Json
    if (-not $settings.error_recovery_enabled) {{
        exit 0
    }}

    # 读取输入
    $stdinLines = @()
    $timeout = 5
    $startTime = Get-Date
    while ($null -ne ($line = [Console]::ReadLine())) {{
        $stdinLines += $line
        if (((Get-Date) - $startTime).TotalSeconds -gt $timeout) {{
            break
        }}
    }}
    $stdin = $stdinLines -join "`n"

    if ([string]::IsNullOrWhiteSpace($stdin)) {{
        exit 0
    }}

    $input = $stdin | ConvertFrom-Json
    $errorCode = $input.error_code
    $errorMessage = $input.error_message
    $sessionId = $input.session_id

    # 尝试从嵌套对象提取
    if ($input.error) {{
        if ($input.error.code) {{ $errorCode = $input.error.code }}
        if ($input.error.message) {{ $errorMessage = $input.error.message }}
    }}

    if ([string]::IsNullOrWhiteSpace($errorCode) -and [string]::IsNullOrWhiteSpace($errorMessage)) {{
        exit 0
    }}

    Write-Log "Codex error detected: [$errorCode] $errorMessage" "INFO"

    # 分类错误
    $errorType = Get-ErrorType -ErrorCode $errorCode -ErrorMessage $errorMessage
    Write-Log "Error type: $errorType" "INFO"

    # 检查恢复次数
    $stateDir = Split-Path $settingsPath
    $statePath = Join-Path $stateDir "error_recovery_state.json"
    $state = @{{}}
    if (Test-Path $statePath) {{
        try {{
            $state = Get-Content $statePath -Raw | ConvertFrom-Json -AsHashtable
        }} catch {{
            $state = @{{}}
        }}
    }}

    $recoveryKey = "$sessionId-$errorType"
    $recoveryCount = if ($state.ContainsKey($recoveryKey)) {{ $state[$recoveryKey] }} else {{ 0 }}
    $maxRecoveries = if ($settings.max_error_recoveries) {{ $settings.max_error_recoveries }} else {{ 3 }}

    if ($recoveryCount -ge $maxRecoveries) {{
        Write-Log "Max recoveries reached for $errorType" "WARN"

        # 记录日志
        $logPath = Join-Path $stateDir "error_recovery_log.jsonl"
        $logEntry = @{{
            timestamp = (Get-Date -Format "o")
            session_id = $sessionId
            error_type = $errorType
            error_code = $errorCode
            error_message = $errorMessage
            action = "max_recoveries_reached"
            recovery_count = $recoveryCount
        }} | ConvertTo-Json -Compress
        Add-Content -Path $logPath -Value $logEntry -ErrorAction SilentlyContinue

        exit 0
    }}

    # 更新恢复次数
    $recoveryCount++
    $state[$recoveryKey] = $recoveryCount
    try {{
        $tempPath = "$statePath.tmp"
        $state | ConvertTo-Json | Set-Content $tempPath
        Move-Item -Path $tempPath -Destination $statePath -Force
    }} catch {{
        Write-Log "Failed to save state: $_" "ERROR"
    }}

    # 记录恢复尝试
    $logPath = Join-Path $stateDir "error_recovery_log.jsonl"
    $logEntry = @{{
        timestamp = (Get-Date -Format "o")
        session_id = $sessionId
        error_type = $errorType
        error_code = $errorCode
        error_message = $errorMessage
        action = "attempting_recovery"
        recovery_count = $recoveryCount
    }} | ConvertTo-Json -Compress
    Add-Content -Path $logPath -Value $logEntry -ErrorAction SilentlyContinue

    # 根据错误类型选择恢复策略
    $output = $null

    if ($errorType -eq "content_length") {{
        # Codex CLI 使用 /compress 命令
        $output = @{{
            recover = $true
            commands = @("/compress", "继续")
            userMessage = "对话内容过长，正在自动压缩并继续..."
        }} | ConvertTo-Json
        Write-Log "Recovery: /compress + continue" "INFO"

    }} elseif ($errorType -eq "rate_limit") {{
        # 等待后重试
        $waitSeconds = 60
        if ($errorMessage -match '(\\d+)\\s*秒') {{
            $waitSeconds = [int]$Matches[1]
        }}
        $output = @{{
            recover = $true
            wait = $waitSeconds
            commands = @("继续")
            userMessage = "请求过于频繁，等待 $waitSeconds 秒后重试..."
        }} | ConvertTo-Json
        Write-Log "Recovery: wait $waitSeconds seconds + continue" "INFO"

    }} elseif ($errorType -in @("timeout", "overload")) {{
        # 指数退避
        $backoffSeconds = [Math]::Min(5 * [Math]::Pow(2, $recoveryCount - 1), 60)
        $output = @{{
            recover = $true
            wait = $backoffSeconds
            commands = @("继续")
            userMessage = "服务暂时不可用，等待 $backoffSeconds 秒后重试..."
        }} | ConvertTo-Json
        Write-Log "Recovery: backoff $backoffSeconds seconds + continue" "INFO"

    }} elseif ($errorType -in @("auth", "quota")) {{
        # 通知用户
        $userMsg = if ($errorType -eq "auth") {{ "认证失败，请检查 API 密钥" }} else {{ "配额已用完，请充值" }}
        $output = @{{
            recover = $false
            notify = $true
            userMessage = $userMsg
        }} | ConvertTo-Json
        Write-Log "Notify user: $userMsg" "INFO"
    }}

    if ($output) {{
        Write-Output $output
    }}

}} catch {{
    Write-Log "Error in Codex recovery hook: $_" "ERROR"
    exit 0
}}

exit 0
'''

    return script
