"""
Enhanced PowerShell hook script generator with robust error handling.
"""

from core.auto_continue.error_patterns import RECOVERABLE_API_ERROR_PATTERNS
from models.auto_continue import (
    DEFAULT_TRAINING_COMPLETION_PATTERNS,
    DEFAULT_TRAINING_CONTEXT_PATTERNS,
    DEFAULT_TRAINING_SKIP_PATTERNS,
)


def _powershell_array(values: list[str], indent: int = 12) -> str:
    prefix = " " * indent
    lines = [prefix + "'" + value.replace("'", "''") + "'" for value in values]
    return ",\n".join(lines)


POWERSHELL_BOOL_HELPERS = r'''function ConvertTo-Bool {
    param($Value, [bool]$Default = $false)

    if ($null -eq $Value) { return $Default }
    if ($Value -is [bool]) { return $Value }
    if ($Value -is [byte] -or $Value -is [int] -or $Value -is [long] -or $Value -is [double]) {
        return [bool]$Value
    }

    $text = ([string]$Value).Trim().ToLowerInvariant()
    if ($text -in @("1", "true", "yes", "on")) { return $true }
    if ($text -in @("0", "false", "no", "off")) { return $false }
    return $Default
}

function Get-BoolSetting {
    param($Settings, [string]$Name, [bool]$Default = $false)

    if ($null -eq $Settings -or $null -eq $Settings.PSObject.Properties[$Name]) {
        return $Default
    }
    return ConvertTo-Bool -Value $Settings.PSObject.Properties[$Name].Value -Default $Default
}

function Get-StringSetting {
    param($Settings, [string]$Name, [string]$Default = "")

    if ($null -eq $Settings -or $null -eq $Settings.PSObject.Properties[$Name]) {
        return $Default
    }
    $value = [string]$Settings.PSObject.Properties[$Name].Value
    if ([string]::IsNullOrWhiteSpace($value)) {
        return $Default
    }
    return $value.Trim()
}'''


def generate_hook_script(settings_path: str, enable_git: bool = True) -> str:
    """Generate the PowerShell hook script with enhanced error handling."""
    git_enabled = "$true" if enable_git else "$false"

    script = f'''# Auto-continue hook script
# Generated by API切换器
# Enhanced with robust error handling

$ErrorActionPreference = "Stop"
$gitSnapshotEnabled = {git_enabled}

# Logging function
function Write-Log {{
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logMessage = "$timestamp [$Level] $Message"
    [Console]::Error.WriteLine($logMessage)
}}

function Initialize-Utf8Console {{
    try {{
        $utf8NoBom = New-Object System.Text.UTF8Encoding -ArgumentList $false
        [Console]::InputEncoding = $utf8NoBom
        [Console]::OutputEncoding = $utf8NoBom
        $script:OutputEncoding = $utf8NoBom
        $global:OutputEncoding = $utf8NoBom
    }} catch {{
        Write-Log "Failed to configure UTF-8 console encoding: $_" "WARN"
    }}
}}

Initialize-Utf8Console

function Read-HookInput {{
    try {{
        $stdinStream = [Console]::OpenStandardInput()
        $reader = New-Object System.IO.StreamReader($stdinStream, [System.Text.Encoding]::UTF8, $true)
        return $reader.ReadToEnd()
    }} catch {{
        Write-Log "Failed to read hook input as UTF-8 stream: $_" "WARN"
        return [Console]::In.ReadToEnd()
    }}
}}

function Add-HookDirectoryCandidate {{
    param(
        [System.Collections.ArrayList]$Candidates,
        $Value
    )

    if ($null -eq $Value) {{
        return
    }}

    if ($Value -is [System.Array]) {{
        foreach ($item in $Value) {{
            Add-HookDirectoryCandidate -Candidates $Candidates -Value $item
        }}
        return
    }}

    if ($Value -is [System.Collections.IDictionary]) {{
        foreach ($key in @(
            "cwd",
            "uri",
            "path",
            "dir",
            "directory",
            "root",
            "workspace",
            "workspace_dir",
            "workspaceDir",
            "workspace_folders",
            "workspaceFolders",
            "project_dir",
            "projectDir",
            "project_path",
            "projectPath",
            "project_root",
            "projectRoot",
            "repo_path",
            "repoPath",
            "repo_root",
            "repoRoot",
            "repository_path",
            "repositoryPath",
            "repository_root",
            "repositoryRoot",
            "root_path",
            "rootPath"
        )) {{
            if ($Value.Contains($key)) {{
                Add-HookDirectoryCandidate -Candidates $Candidates -Value $Value[$key]
            }}
        }}
        return
    }}

    if ($Value -isnot [string] -and $Value.PSObject -and $Value.PSObject.Properties) {{
        foreach ($key in @(
            "cwd",
            "uri",
            "path",
            "dir",
            "directory",
            "root",
            "workspace",
            "workspace_dir",
            "workspaceDir",
            "workspace_folders",
            "workspaceFolders",
            "project_dir",
            "projectDir",
            "project_path",
            "projectPath",
            "project_root",
            "projectRoot",
            "repo_path",
            "repoPath",
            "repo_root",
            "repoRoot",
            "repository_path",
            "repositoryPath",
            "repository_root",
            "repositoryRoot",
            "root_path",
            "rootPath"
        )) {{
            $property = $Value.PSObject.Properties[$key]
            if ($null -ne $property) {{
                Add-HookDirectoryCandidate -Candidates $Candidates -Value $property.Value
            }}
        }}
        return
    }}

    $text = [string]$Value
    if (-not [string]::IsNullOrWhiteSpace($text)) {{
        [void]$Candidates.Add($text)
    }}
}}

function Resolve-HookProjectDirectory {{
    param($HookInput)

    $candidates = New-Object System.Collections.ArrayList
    foreach ($fieldName in @(
        "cwd",
        "uri",
        "current_directory",
        "currentDirectory",
        "current_working_directory",
        "currentWorkingDirectory",
        "workspace",
        "workspace_dir",
        "workspaceDir",
        "workspace_folders",
        "workspaceFolders",
        "project_dir",
        "projectDir",
        "project_path",
        "projectPath",
        "project_root",
        "projectRoot",
        "repo_path",
        "repoPath",
        "repo_root",
        "repoRoot",
        "repository_path",
        "repositoryPath",
        "repository_root",
        "repositoryRoot",
        "root",
        "root_dir",
        "rootDir",
        "root_path",
        "rootPath"
    )) {{
        $property = $HookInput.PSObject.Properties[$fieldName]
        if ($null -ne $property) {{
            Add-HookDirectoryCandidate -Candidates $candidates -Value $property.Value
        }}
    }}

    foreach ($containerName in @("workspace", "project", "repository", "repo", "context")) {{
        $property = $HookInput.PSObject.Properties[$containerName]
        if ($null -ne $property) {{
            Add-HookDirectoryCandidate -Candidates $candidates -Value $property.Value
        }}
    }}

    foreach ($candidate in $candidates) {{
        try {{
            $pathText = Convert-HookDirectoryCandidateToPath -Candidate ([string]$candidate)
            if ([string]::IsNullOrWhiteSpace($pathText)) {{
                continue
            }}
            if (Test-Path -LiteralPath $pathText -PathType Container) {{
                return (Resolve-Path -LiteralPath $pathText -ErrorAction Stop).Path
            }}
        }} catch {{
            Write-Log "Ignoring invalid hook project directory candidate: $candidate" "WARN"
        }}
    }}

    return ""
}}

function Convert-HookDirectoryCandidateToPath {{
    param([string]$Candidate)

    if ([string]::IsNullOrWhiteSpace($Candidate)) {{
        return ""
    }}

    $pathText = ([string]$Candidate).Trim().Trim('"').Trim("'")
    if ([string]::IsNullOrWhiteSpace($pathText)) {{
        return ""
    }}

    if ($pathText -match "(?i)^file://") {{
        try {{
            $uri = [System.Uri]$pathText
            if ($uri.IsFile) {{
                return $uri.LocalPath
            }}
        }} catch {{
            Write-Log "Ignoring invalid file URI hook project directory candidate: $Candidate" "WARN"
        }}
        return ""
    }}

    $pathText = [Environment]::ExpandEnvironmentVariables($pathText)
    if ($pathText -eq "~" -or $pathText.StartsWith("~/") -or $pathText.StartsWith("~\")) {{
        try {{
            $home = [Environment]::GetFolderPath("UserProfile")
            if (-not [string]::IsNullOrWhiteSpace($home)) {{
                if ($pathText.Length -eq 1) {{
                    return $home
                }}
                return (Join-Path $home $pathText.Substring(2))
            }}
        }} catch {{
            Write-Log "Failed to expand home directory candidate: $Candidate" "WARN"
        }}
    }}

    return $pathText
}}

function Use-HookProjectDirectory {{
    param($HookInput)

    $projectDir = Resolve-HookProjectDirectory -HookInput $HookInput
    if ([string]::IsNullOrWhiteSpace($projectDir)) {{
        return
    }}
    try {{
        Set-Location -LiteralPath $projectDir -ErrorAction Stop
        Write-Log "Using hook project directory for Git snapshot: $projectDir" "INFO"
    }} catch {{
        Write-Log ("Failed to switch to hook project directory {{0}}: {{1}}" -f $projectDir, $_) "WARN"
    }}
}}

function ConvertTo-Hashtable {{
    param($Value)

    $result = @{{}}
    if ($null -eq $Value) {{ return $result }}
    if ($Value -is [System.Collections.IDictionary]) {{ return $Value }}
    if ($Value.PSObject -and $Value.PSObject.Properties) {{
        foreach ($prop in $Value.PSObject.Properties) {{
            $result[$prop.Name] = $prop.Value
        }}
    }}
    return $result
}}

{POWERSHELL_BOOL_HELPERS}

# Text matching and decision logging helpers.
function Get-NormalizedText {{
    param([string]$Text)

    if ($null -eq $Text) {{
        return ""
    }}

    return ($Text -replace "\\s+", " ").Trim()
}}

function Find-MatchingRegex {{
    param(
        [string]$Text,
        $Patterns
    )

    if ($null -eq $Patterns) {{
        return $null
    }}

    foreach ($pattern in $Patterns) {{
        $patternText = [string]$pattern
        if ([string]::IsNullOrWhiteSpace($patternText)) {{
            continue
        }}
        try {{
            if ([regex]::IsMatch($Text, $patternText, [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)) {{
                return $patternText
            }}
        }} catch {{
            Write-Log "Invalid regex pattern ignored: $patternText" "WARN"
        }}
    }}

    return $null
}}

function Save-StateFile {{
    param(
        [string]$Path,
        [hashtable]$State
    )

    try {{
        $tempPath = "$Path.tmp"
        $State | ConvertTo-Json | Set-Content -LiteralPath $tempPath -Encoding UTF8 -ErrorAction Stop
        Move-Item -LiteralPath $tempPath -Destination $Path -Force -ErrorAction Stop
        return $true
    }} catch {{
        Write-Log "Failed to save state: $_" "WARN"
        return $false
    }}
}}

function Write-DecisionLog {{
    param(
        [string]$StateDir,
        [string]$SessionId,
        [string]$HookEvent,
        [string]$AgentId,
        [string]$Decision,
        [string]$Reason,
        [string]$Match = "",
        [string]$Message = "",
        [int]$Count = -1,
        [string]$ContinuationPrompt = "",
        [string]$GitCommitHash = ""
    )

    try {{
        if (-not (Test-Path -LiteralPath $StateDir)) {{
            New-Item -ItemType Directory -Force -Path $StateDir | Out-Null
        }}
        $excerpt = [string]$Message
        if ($excerpt.Length -gt 500) {{
            $excerpt = $excerpt.Substring(0, 500)
        }}
        $entry = [ordered]@{{
            timestamp = (Get-Date -Format "o")
            session_id = $SessionId
            hook_event = $HookEvent
            agent_id = $AgentId
            decision = $Decision
            reason = $Reason
            match = $Match
            count = $Count
            excerpt = $excerpt
        }}
        if (-not [string]::IsNullOrWhiteSpace($ContinuationPrompt)) {{
            $entry["continuation_prompt"] = $ContinuationPrompt
        }}
        if (-not [string]::IsNullOrWhiteSpace($GitCommitHash)) {{
            $entry["git_commit_hash"] = $GitCommitHash
        }}
        $logPath = Join-Path $StateDir "auto_continue_stop_log.jsonl"
        $logEntry = $entry | ConvertTo-Json -Compress -Depth 6
        Add-Content -LiteralPath $logPath -Value $logEntry -Encoding UTF8 -ErrorAction Stop
    }} catch {{
        Write-Log "Failed to write decision log: $_" "WARN"
    }}
}}

function Get-TrainingContinuationPrompt {{
    param($Settings)

    $custom = Get-StringSetting -Settings $Settings -Name "training_continue_prompt" -Default ""
    if ([string]::IsNullOrWhiteSpace($custom)) {{
        $custom = "\u8bf7\u68c0\u67e5\u5f53\u524d\u6df1\u5ea6\u5b66\u4e60/\u6a21\u578b\u8bad\u7ec3\u4efb\u52a1\u7684\u6700\u65b0\u8bc4\u4f30\u7ed3\u679c\u3001\u8bad\u7ec3\u65e5\u5fd7\u3001\u6307\u6807\u548c\u6a21\u578b\u4ea7\u7269\u3002"
    }}

    return @"
\u8bf7\u68c0\u67e5\u5f53\u524d\u6df1\u5ea6\u5b66\u4e60/\u6a21\u578b\u8bad\u7ec3\u4efb\u52a1\u7684\u6700\u65b0\u8bc4\u4f30\u7ed3\u679c\u3001\u8bad\u7ec3\u65e5\u5fd7\u3001\u6307\u6807\u548c\u6a21\u578b\u4ea7\u7269\u3002

\u7528\u6237\u5b9a\u4e49\u7684\u8bad\u7ec3\u76ee\u6807/\u7eed\u8dd1\u8981\u6c42\uff1a
$custom

\u5982\u679c\u5c1a\u672a\u8fbe\u6807\uff0c\u8bf7\u7ee7\u7eed\u8bad\u7ec3\u3001\u8c03\u53c2\u3001\u6539\u8fdb\u6a21\u578b\u6216\u8865\u5145\u9a8c\u8bc1\uff0c\u5e76\u8bb0\u5f55\u65b0\u7684\u8bc4\u4f30\u7ed3\u679c\u3002
\u5982\u679c\u5df2\u8fbe\u6807\uff0c\u8bf7\u505c\u6b62\u7eed\u8dd1\uff0c\u5e76\u5728\u6700\u7ec8\u56de\u590d\u4e2d\u660e\u786e\u5199\u51fa TRAINING_TARGET_MET\uff0c\u540c\u65f6\u5217\u51fa\u5173\u952e\u6307\u6807\u548c\u6a21\u578b\u4ea7\u7269\u8def\u5f84\u3002
"@
}}

# Git snapshot helpers.
function Ensure-LocalGitIgnore {{
    try {{
        $gitignorePath = Join-Path (Get-Location) ".gitignore"
        if (Test-Path $gitignorePath) {{
            return
        }}

        @(
            "# Python",
            "__pycache__/",
            "*.py[cod]",
            "build/",
            "dist/",
            ".venv/",
            "venv/",
            "env/",
            "",
            "# Dependency caches / generated output",
            "node_modules/",
            ".next/",
            ".nuxt/",
            "target/",
            ".cache/",
            ".pytest_cache/",
            ".ruff_cache/",
            ".mypy_cache/",
            "coverage/",
            ".coverage",
            "",
            "# Local secrets",
            ".env",
            ".env.*",
            "!.env.example",
            "!.env.sample",
            "",
            "# Logs",
            "*.log",
            "logs/"
        ) | Set-Content -Path $gitignorePath -Encoding UTF8
        Write-Log "Created local .gitignore for Git snapshots" "INFO"
    }} catch {{
        Write-Log "Failed to create local .gitignore: $_" "WARN"
    }}
}}

function Create-GitSnapshot {{
    param([string]$Message = "Auto snapshot before continue")

    $previousErrorActionPreference = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    try {{
        if ($null -eq (Get-Command git -ErrorAction SilentlyContinue)) {{
            Write-Log "Git command is not available; skipping git snapshot" "WARN"
            return ""
        }}

        # 检查是否是git仓库
        $isGitRepo = git rev-parse --git-dir 2>$null
        $initializedRepo = $false
        if (-not $isGitRepo) {{
            # 初始化git仓库
            git init 2>&1 | Out-Null
            if ($LASTEXITCODE -ne 0) {{
                Write-Log "Git init did not complete; skipping git snapshot" "WARN"
                return ""
            }}
            $initializedRepo = $true
            Write-Log "Initialized git repository" "INFO"
        }}

        if ($initializedRepo) {{
            Ensure-LocalGitIgnore
        }}

        $gitDir = git rev-parse --git-dir 2>$null
        if (-not [string]::IsNullOrWhiteSpace($gitDir)) {{
            $indexLockPath = Join-Path $gitDir "index.lock"
            if (Test-Path $indexLockPath) {{
                Write-Log "Git index lock exists; skipping git snapshot" "WARN"
                return ""
            }}
        }}

        # 检查是否有更改
        $status = git status --porcelain 2>$null
        if ([string]::IsNullOrWhiteSpace($status)) {{
            Write-Log "No changes to commit" "INFO"
            return ""
        }}

        # 添加所有更改
        git add -A 2>&1 | Out-Null
        if ($LASTEXITCODE -ne 0) {{
            Write-Log "Git add did not complete; skipping git snapshot" "WARN"
            return ""
        }}

        # 检查git配置
        $userName = git config user.name 2>$null
        $userEmail = git config user.email 2>$null
        if ([string]::IsNullOrWhiteSpace($userName) -or [string]::IsNullOrWhiteSpace($userEmail)) {{
            git config user.name "API-Switcher-Auto" 2>&1 | Out-Null
            git config user.email "auto@api-switcher.local" 2>&1 | Out-Null
            Write-Log "Configured git user" "INFO"
        }}

        # 提交
        $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        $commitMsg = "[$Message] $timestamp"
        git commit --no-verify -m $commitMsg 2>&1 | Out-Null
        if ($LASTEXITCODE -ne 0) {{
            Write-Log "Git snapshot commit did not complete" "WARN"
            return ""
        }}

        # 获取commit hash
        $commitHash = git rev-parse --short HEAD 2>$null
        Write-Log "Created git snapshot: $commitHash" "INFO"
        return [string]$commitHash

    }} catch {{
        Write-Log "Failed to create git snapshot: $_" "WARN"
        return ""
    }} finally {{
        $ErrorActionPreference = $previousErrorActionPreference
    }}
}}

try {{
    # Read settings with error handling
    $settingsPath = "{settings_path}"
    if (-not (Test-Path $settingsPath)) {{
        Write-Log "Settings file not found: $settingsPath" "WARN"
        exit 0  # Allow stop if no settings
    }}

    try {{
        $settings = Get-Content $settingsPath -Raw -Encoding UTF8 -ErrorAction Stop | ConvertFrom-Json -ErrorAction Stop
    }} catch {{
        Write-Log "Failed to parse settings JSON: $_" "ERROR"
        exit 0  # Allow stop if settings invalid
    }}

    $configDir = Split-Path -Parent $settingsPath
    $stateDir = Join-Path $configDir "tmp"
    try {{
        if (-not (Test-Path -LiteralPath $stateDir)) {{
            New-Item -ItemType Directory -Force -Path $stateDir | Out-Null
        }}
    }} catch {{
        Write-Log "Failed to create tmp state directory, falling back to config dir: $_" "WARN"
        $stateDir = $configDir
    }}

    $autoContinueEnabled = Get-BoolSetting -Settings $settings -Name "enabled" -Default $false
    $trainingAutoContinueEnabled = Get-BoolSetting -Settings $settings -Name "training_auto_continue_enabled" -Default $false
    $gitAutoSnapshot = Get-BoolSetting -Settings $settings -Name "git_auto_snapshot" -Default $gitSnapshotEnabled
    $gitSnapshotOnStart = Get-BoolSetting -Settings $settings -Name "git_snapshot_on_start" -Default $gitSnapshotEnabled
    $autoApprovePermissionRequests = Get-BoolSetting -Settings $settings -Name "auto_approve_permission_requests" -Default $false

    if (-not $autoContinueEnabled -and -not $trainingAutoContinueEnabled -and -not $autoApprovePermissionRequests -and -not ($gitAutoSnapshot -and $gitSnapshotOnStart)) {{
        exit 0
    }}

    # Read stdin (hook input)
    $stdin = Read-HookInput

    if ([string]::IsNullOrWhiteSpace($stdin)) {{
        exit 0  # Allow stop if no input
    }}

    # Parse input JSON with error handling
    try {{
        $hookInput = $stdin | ConvertFrom-Json -ErrorAction Stop
    }} catch {{
        Write-Log "Failed to parse input JSON: $_" "ERROR"
        exit 0
    }}
    Use-HookProjectDirectory -HookInput $hookInput

    # Get session ID, event name, and the final assistant text. New Codex builds
    # use the same last_assistant_message shape as Claude-style Stop hooks.
    $sessionId = if ($hookInput.session_id) {{ $hookInput.session_id }} elseif ($hookInput.sessionId) {{ $hookInput.sessionId }} else {{ "" }}
    $hookEvent = if ($hookInput.hook_event_name) {{ $hookInput.hook_event_name }} elseif ($hookInput.hookEventName) {{ $hookInput.hookEventName }} else {{ "Stop" }}
    $agentId = if ($hookInput.agent_id) {{ $hookInput.agent_id }} elseif ($hookInput.agentId) {{ $hookInput.agentId }} else {{ $null }}
    $isClaude = $null -ne $hookInput.hook_event_name -or $null -ne $hookInput.hookEventName

    $lastMessage = ""
    foreach ($fieldName in @(
        "last_assistant_message",
        "lastAssistantMessage",
        "last_message",
        "lastMessage",
        "assistant_message",
        "assistantMessage",
        "message",
        "content",
        "text"
    )) {{
        $property = $hookInput.PSObject.Properties[$fieldName]
        if ($null -ne $property -and -not [string]::IsNullOrWhiteSpace([string]$property.Value)) {{
            $lastMessage = [string]$property.Value
            break
        }}
    }}
    $lastMessage = Get-NormalizedText $lastMessage

    $gitSnapshotAttempted = $false
    $gitSnapshotHash = ""
    $promptSnapshotEvents = @("UserPromptSubmit", "SessionStart")
    if ($promptSnapshotEvents -contains $hookEvent) {{
        if ($gitAutoSnapshot -and $gitSnapshotOnStart) {{
            Write-Log "Creating git snapshot on prompt/session start hook..." "INFO"
            $gitSnapshotHash = Create-GitSnapshot -Message "git-snapshot"
            $gitSnapshotAttempted = $true
        }}
        exit 0
    }}

    # Stop hooks are the broadest safety net: they cover normal manual turns,
    # auto-continue turns, and older Codex builds that do not emit prompt hooks.
    $stopSnapshotEvents = @("Stop", "SubagentStop")
    if (($stopSnapshotEvents -contains $hookEvent) -and $gitAutoSnapshot -and $gitSnapshotOnStart) {{
        Write-Log "Creating git snapshot on stop hook..." "INFO"
        $gitSnapshotHash = Create-GitSnapshot -Message "git-snapshot"
        $gitSnapshotAttempted = $true
    }}

    if ($isClaude -and ($hookEvent -eq "PermissionRequest" -or $hookEvent -eq "PreToolUse")) {{
        if (-not $autoApprovePermissionRequests) {{
            exit 0
        }}

        $toolName = ""
        if ($hookInput.tool_name) {{ $toolName = [string]$hookInput.tool_name }}
        elseif ($hookInput.toolName) {{ $toolName = [string]$hookInput.toolName }}
        elseif ($hookInput.tool) {{ $toolName = [string]$hookInput.tool }}
        elseif ($hookInput.permission_request -and $hookInput.permission_request.tool_name) {{ $toolName = [string]$hookInput.permission_request.tool_name }}
        elseif ($hookInput.permission_request -and $hookInput.permission_request.toolName) {{ $toolName = [string]$hookInput.permission_request.toolName }}
        elseif ($hookInput.permissionRequest -and $hookInput.permissionRequest.tool_name) {{ $toolName = [string]$hookInput.permissionRequest.tool_name }}
        elseif ($hookInput.permissionRequest -and $hookInput.permissionRequest.toolName) {{ $toolName = [string]$hookInput.permissionRequest.toolName }}
        elseif ($hookInput.request -and $hookInput.request.tool_name) {{ $toolName = [string]$hookInput.request.tool_name }}
        elseif ($hookInput.request -and $hookInput.request.toolName) {{ $toolName = [string]$hookInput.request.toolName }}

        if ([string]::IsNullOrWhiteSpace($toolName)) {{
            exit 0
        }}

        $legacyBashAllowed = Get-BoolSetting -Settings $settings -Name "auto_approve_bash" -Default $true
        if ($null -eq $settings.PSObject.Properties["auto_approve_tools"]) {{
            $allowedTools = if ($legacyBashAllowed) {{
                @("Bash", "Edit", "MultiEdit", "Write", "NotebookEdit")
            }} else {{
                @("Edit", "MultiEdit", "Write", "NotebookEdit")
            }}
        }} else {{
            $allowedTools = @()
            foreach ($tool in $settings.auto_approve_tools) {{
                $toolText = [string]$tool
                if (-not [string]::IsNullOrWhiteSpace($toolText)) {{
                    $allowedTools += $toolText.Trim()
                }}
            }}
            if ($legacyBashAllowed -and $allowedTools.Count -gt 0) {{
                $hasBash = $false
                foreach ($allowed in $allowedTools) {{
                    if ($allowed -ieq "Bash") {{
                        $hasBash = $true
                        break
                    }}
                }}
                if (-not $hasBash) {{
                    $allowedTools = @("Bash") + $allowedTools
                }}
            }}
        }}

        $isAllowedTool = $false
        foreach ($allowed in $allowedTools) {{
            $allowedText = [string]$allowed
            $ruleToolName = $allowedText
            $parenIndex = $allowedText.IndexOf("(")
            if ($parenIndex -gt 0) {{
                $ruleToolName = $allowedText.Substring(0, $parenIndex)
            }}
            if ($allowedText -eq "*" -or $toolName -ieq $allowedText -or $toolName -like $allowedText -or $toolName -ieq $ruleToolName) {{
                $isAllowedTool = $true
                break
            }}
        }}
        if (-not $isAllowedTool) {{
            exit 0
        }}

        $autoApproveMax = 0
        if ($null -ne $settings.PSObject.Properties["auto_approve_max_per_session"]) {{
            try {{ $autoApproveMax = [int]$settings.auto_approve_max_per_session }} catch {{ $autoApproveMax = 0 }}
        }}
        if ($autoApproveMax -lt 0) {{ $autoApproveMax = 0 }}

        $logPath = Join-Path $stateDir "auto_continue_stop_log.jsonl"
        $count = 0

        if ($autoApproveMax -gt 0) {{
            $permissionStatePath = Join-Path $stateDir "auto_continue_permission_state.json"
            $permissionLockPath = "$permissionStatePath.lock"
            $permissionLockStream = $null
            $permissionLockWait = 0
            while ($null -eq $permissionLockStream -and $permissionLockWait -lt 5) {{
                try {{
                    $permissionLockStream = [System.IO.File]::Open(
                        $permissionLockPath,
                        [System.IO.FileMode]::CreateNew,
                        [System.IO.FileAccess]::Write,
                        [System.IO.FileShare]::None
                    )
                }} catch [System.IO.IOException] {{
                    try {{
                        if ((Test-Path $permissionLockPath) -and ((Get-Date) - (Get-Item $permissionLockPath).LastWriteTime).TotalSeconds -gt 15) {{
                            Remove-Item -Path $permissionLockPath -Force -ErrorAction SilentlyContinue
                            continue
                        }}
                    }} catch {{
                        # Ignore stale-lock inspection errors and wait.
                    }}
                    Start-Sleep -Milliseconds 50
                    $permissionLockWait++
                }} catch {{
                    Write-Log "Failed to create permission lock file: $_" "WARN"
                    exit 0
                }}
            }}

            if ($null -eq $permissionLockStream) {{
                Write-Log "Failed to acquire permission state lock" "WARN"
                exit 0
            }}

            try {{
                $permissionState = @{{}}
                if (Test-Path $permissionStatePath) {{
                    try {{
                        $permissionStateContent = Get-Content $permissionStatePath -Raw -Encoding UTF8 -ErrorAction Stop
                        $permissionState = ConvertTo-Hashtable ($permissionStateContent | ConvertFrom-Json -ErrorAction Stop)
                    }} catch {{
                        Write-Log "Failed to parse permission state JSON, resetting state: $_" "WARN"
                        $permissionState = @{{}}
                    }}
                }}

                $permissionStateKey = "$sessionId-PermissionRequest-$agentId"
                $count = if ($permissionState.ContainsKey($permissionStateKey)) {{ $permissionState[$permissionStateKey] }} else {{ 0 }}
                if ($count -ge $autoApproveMax) {{
                    $logEntry = @{{
                        timestamp = (Get-Date -Format "o")
                        session_id = $sessionId
                        hook_event = $hookEvent
                        agent_id = $agentId
                        tool_name = $toolName
                        decision = "ask_user"
                        reason = "auto_approve_limit_reached"
                        count = $count
                    }} | ConvertTo-Json -Compress
                    try {{ Add-Content -Path $logPath -Value $logEntry -ErrorAction Stop }} catch {{ Write-Log "Failed to write log: $_" "WARN" }}
                    exit 0
                }}

                $count++
                $permissionState[$permissionStateKey] = $count
                try {{
                    $tempPath = "$permissionStatePath.tmp"
                    $permissionState | ConvertTo-Json | Set-Content $tempPath -ErrorAction Stop
                    Move-Item -Path $tempPath -Destination $permissionStatePath -Force -ErrorAction Stop
                }} catch {{
                    Write-Log "Failed to save permission auto-approve state: $_" "WARN"
                }}
            }} finally {{
                if ($null -ne $permissionLockStream) {{
                    try {{ $permissionLockStream.Dispose() }} catch {{ }}
                }}
                if (Test-Path $permissionLockPath) {{
                    try {{ Remove-Item -Path $permissionLockPath -Force -ErrorAction SilentlyContinue }} catch {{ }}
                }}
            }}
        }}

        $logEntry = @{{
            timestamp = (Get-Date -Format "o")
            session_id = $sessionId
            hook_event = $hookEvent
            agent_id = $agentId
            tool_name = $toolName
            decision = "auto_approve"
            reason = "configured_permission_request"
            count = $count
        }} | ConvertTo-Json -Compress
        try {{ Add-Content -Path $logPath -Value $logEntry -ErrorAction Stop }} catch {{ Write-Log "Failed to write log: $_" "WARN" }}

        $updatedPermissions = @()
        if ($hookEvent -eq "PermissionRequest") {{
            $suggestions = $null
            if ($hookInput.PSObject.Properties["permission_suggestions"]) {{
                $suggestions = $hookInput.permission_suggestions
            }} elseif ($hookInput.PSObject.Properties["permissionSuggestions"]) {{
                $suggestions = $hookInput.permissionSuggestions
            }}
            if ($null -eq $suggestions) {{
                foreach ($containerName in @("permission_request", "permissionRequest", "request")) {{
                    $containerProperty = $hookInput.PSObject.Properties[$containerName]
                    if ($null -eq $containerProperty) {{ continue }}
                    $container = $containerProperty.Value
                    if ($null -eq $container) {{ continue }}
                    if ($container.PSObject.Properties["permission_suggestions"]) {{
                        $suggestions = $container.permission_suggestions
                        break
                    }} elseif ($container.PSObject.Properties["permissionSuggestions"]) {{
                        $suggestions = $container.permissionSuggestions
                        break
                    }}
                }}
            }}

            if ($null -ne $suggestions) {{
                if ($suggestions -is [System.Array]) {{
                    foreach ($suggestion in $suggestions) {{
                        if ($null -ne $suggestion) {{
                            $updatedPermissions += $suggestion
                        }}
                    }}
                }} else {{
                    $updatedPermissions += $suggestions
                }}
            }}

            if ($updatedPermissions.Count -eq 0) {{
                $updatedPermissions += @{{
                    type = "addRules"
                    rules = @(
                        @{{
                            toolName = $toolName
                        }}
                    )
                    behavior = "allow"
                    destination = "session"
                }}
            }}

            $updatedPermissions += @{{
                type = "setMode"
                mode = "dontAsk"
                destination = "session"
            }}
        }}

        if ($hookEvent -eq "PreToolUse") {{
            $output = @{{
                hookSpecificOutput = @{{
                    hookEventName = "PreToolUse"
                    permissionDecision = "allow"
                    permissionDecisionReason = "Auto-approved by API Switcher"
                }}
            }} | ConvertTo-Json -Depth 8
        }} else {{
            $output = @{{
                hookSpecificOutput = @{{
                    hookEventName = "PermissionRequest"
                    decision = @{{
                        behavior = "allow"
                        updatedPermissions = $updatedPermissions
                }}
            }}
            }} | ConvertTo-Json -Depth 8
        }}
        Write-Output $output
        exit 0
    }}

    if (-not $autoContinueEnabled -and -not $trainingAutoContinueEnabled) {{
        exit 0  # Allow stop if continue modes are disabled
    }}

    # Validate settings
    if ($null -eq $settings.max_continuations -or $settings.max_continuations -lt -1) {{
        Write-Log "Invalid max_continuations value" "ERROR"
        exit 0
    }}

    if ([string]::IsNullOrWhiteSpace($lastMessage) -and $hookEvent -ne "PermissionRequest") {{
        exit 0  # Allow stop if no message
    }}

    # Build state key
    $stateKey = "$sessionId-$hookEvent"
    if ($agentId) {{
        $stateKey = "$stateKey-$agentId"
    }}

    # Load state with file locking
    $statePath = Join-Path $stateDir "auto_continue_stop_state.json"
    $logPath = Join-Path $stateDir "auto_continue_stop_log.jsonl"
    $lockPath = "$statePath.lock"

    # Exclusive file-based locking (wait up to 2 seconds)
    $lockStream = $null
    $lockWait = 0
    while ($null -eq $lockStream -and $lockWait -lt 20) {{
        try {{
            $lockStream = [System.IO.File]::Open(
                $lockPath,
                [System.IO.FileMode]::CreateNew,
                [System.IO.FileAccess]::Write,
                [System.IO.FileShare]::None
            )
        }} catch [System.IO.IOException] {{
            try {{
                if ((Test-Path $lockPath) -and ((Get-Date) - (Get-Item $lockPath).LastWriteTime).TotalSeconds -gt 60) {{
                    Remove-Item -Path $lockPath -Force -ErrorAction SilentlyContinue
                    continue
                }}
            }} catch {{
                # Ignore stale-lock inspection errors and wait.
            }}
            Start-Sleep -Milliseconds 100
            $lockWait++
        }} catch {{
            Write-Log "Failed to create lock file: $_" "WARN"
            exit 0
        }}
    }}

    if ($null -eq $lockStream) {{
        Write-Log "Failed to acquire state file lock" "WARN"
        exit 0  # Allow stop if can't acquire lock
    }}

    try {{
        # Load state
        $state = @{{}}
        if (Test-Path $statePath) {{
            try {{
                $stateContent = Get-Content $statePath -Raw -Encoding UTF8 -ErrorAction Stop
                $state = ConvertTo-Hashtable ($stateContent | ConvertFrom-Json -ErrorAction Stop)
            }} catch {{
                Write-Log "Failed to parse state JSON, resetting state: $_" "WARN"
                $state = @{{}}
            }}
        }}

        # Get continuation count
        $count = if ($state.ContainsKey($stateKey)) {{ $state[$stateKey] }} else {{ 0 }}

        if (-not $autoContinueEnabled -and -not $trainingAutoContinueEnabled) {{
            exit 0
        }}

        # Check conservative mode for Claude Code
        if (
            $isClaude -and
            (Get-BoolSetting -Settings $settings -Name "conservative_mode" -Default $true) -and
            (ConvertTo-Bool -Value $hookInput.stop_hook_active -Default $false)
        ) {{
            exit 0  # Allow stop in conservative mode when already continuing
        }}

        # Transient API transport failures should continue even if "error" matches a blocker.
        $recoverableApiErrorPatterns = @(
{_powershell_array(RECOVERABLE_API_ERROR_PATTERNS, 12)}
        )
        $recoverableApiErrorMatch = Find-MatchingRegex -Text $lastMessage -Patterns $recoverableApiErrorPatterns
        $isRecoverableApiError = $null -ne $recoverableApiErrorMatch

        $trainingGuardApplies = $false
        $trainingTargetMetMatch = $null
        $trainingContextMatch = $null
        if ($trainingAutoContinueEnabled) {{
            $trainingCompletionPatterns = @(
{_powershell_array(DEFAULT_TRAINING_COMPLETION_PATTERNS, 16)}
            )
            $trainingTargetMetMatch = Find-MatchingRegex -Text $lastMessage -Patterns $trainingCompletionPatterns
            if ($null -ne $trainingTargetMetMatch) {{
                if ($state.ContainsKey($stateKey)) {{
                    $state.Remove($stateKey)
                    Save-StateFile -Path $statePath -State $state | Out-Null
                }}
                Write-DecisionLog `
                    -StateDir $stateDir `
                    -SessionId $sessionId `
                    -HookEvent $hookEvent `
                    -AgentId $agentId `
                    -Decision "allow_stop" `
                    -Reason "training_target_met" `
                    -Match $trainingTargetMetMatch `
                    -Message $lastMessage `
                    -Count $count `
                    -GitCommitHash $gitSnapshotHash
                exit 0
            }}

            $trainingSkipPatterns = @(
{_powershell_array(DEFAULT_TRAINING_SKIP_PATTERNS, 16)}
            )
            $trainingSkipMatch = Find-MatchingRegex -Text $lastMessage -Patterns $trainingSkipPatterns
            if ($null -ne $trainingSkipMatch) {{
                if ($state.ContainsKey($stateKey)) {{
                    $state.Remove($stateKey)
                    Save-StateFile -Path $statePath -State $state | Out-Null
                }}
                Write-DecisionLog `
                    -StateDir $stateDir `
                    -SessionId $sessionId `
                    -HookEvent $hookEvent `
                    -AgentId $agentId `
                    -Decision "allow_stop" `
                    -Reason "training_not_applicable" `
                    -Match $trainingSkipMatch `
                    -Message $lastMessage `
                    -Count $count `
                    -GitCommitHash $gitSnapshotHash
                exit 0
            }}

            $trainingContextPatterns = @(
{_powershell_array(DEFAULT_TRAINING_CONTEXT_PATTERNS, 16)}
            )
            $trainingContextMatch = Find-MatchingRegex -Text $lastMessage -Patterns $trainingContextPatterns
            $trainingGuardApplies = $null -ne $trainingContextMatch
        }}

        $blockerMatch = Find-MatchingRegex -Text $lastMessage -Patterns $settings.blocker_patterns
        if ($null -ne $blockerMatch -and -not $isRecoverableApiError) {{
            Write-DecisionLog `
                -StateDir $stateDir `
                -SessionId $sessionId `
                -HookEvent $hookEvent `
                -AgentId $agentId `
                -Decision "allow_stop" `
                -Reason "blocker_detected" `
                -Match $blockerMatch `
                -Message $lastMessage `
                -Count $count `
                -GitCommitHash $gitSnapshotHash
            exit 0
        }}

        $incompleteMatch = Find-MatchingRegex -Text $lastMessage -Patterns $settings.incomplete_patterns
        $genericContinueMatch = $autoContinueEnabled -and ($null -ne $incompleteMatch)
        $shouldContinue = $isRecoverableApiError -or $trainingGuardApplies -or $genericContinueMatch
        if (-not $shouldContinue) {{
            if ($state.ContainsKey($stateKey)) {{
                $state.Remove($stateKey)
                Save-StateFile -Path $statePath -State $state | Out-Null
            }}
            $allowReason = if ($trainingAutoContinueEnabled -and -not $autoContinueEnabled) {{ "training_context_not_detected" }} else {{ "no_incomplete_match" }}
            Write-DecisionLog `
                -StateDir $stateDir `
                -SessionId $sessionId `
                -HookEvent $hookEvent `
                -AgentId $agentId `
                -Decision "allow_stop" `
                -Reason $allowReason `
                -Match "" `
                -Message $lastMessage `
                -Count $count `
                -GitCommitHash $gitSnapshotHash
            exit 0
        }}

        $matchedPattern = if ($isRecoverableApiError) {{ $recoverableApiErrorMatch }} elseif ($trainingGuardApplies) {{ $trainingContextMatch }} else {{ $incompleteMatch }}

        # Check max continuations after confirming this stop actually needs continuation.
        if ($settings.max_continuations -ge 0 -and $count -ge $settings.max_continuations) {{
            Write-DecisionLog `
                -StateDir $stateDir `
                -SessionId $sessionId `
                -HookEvent $hookEvent `
                -AgentId $agentId `
                -Decision "allow_stop" `
                -Reason "max_continuations_reached" `
                -Match $matchedPattern `
                -Message $lastMessage `
                -Count $count `
                -GitCommitHash $gitSnapshotHash
            exit 0
        }}

        # Decision: block stop and continue
        $count++
        $state[$stateKey] = $count

        Save-StateFile -Path $statePath -State $state | Out-Null

        $continuationPrompt = if ($trainingGuardApplies -and -not $isRecoverableApiError) {{
            Get-TrainingContinuationPrompt -Settings $settings
        }} else {{
            [string]$settings.continuation_prompt
        }}
        if ([string]::IsNullOrWhiteSpace($continuationPrompt)) {{
            $continuationPrompt = "Please continue from where you left off. Complete any remaining work."
        }}

        $continueReason = if ($isRecoverableApiError) {{ "recoverable_api_error_detected" }} elseif ($trainingGuardApplies) {{ "training_guard_continue" }} else {{ "incomplete_work_detected" }}

        if ($hookEvent -ne "PermissionRequest" -and $hookEvent -ne "PreToolUse" -and $gitAutoSnapshot -and $gitSnapshotOnStart -and -not $gitSnapshotAttempted) {{
            Write-Log "Creating git snapshot before auto-continue..." "INFO"
            $gitSnapshotHash = Create-GitSnapshot -Message "git-snapshot"
        }}

        Write-DecisionLog `
            -StateDir $stateDir `
            -SessionId $sessionId `
            -HookEvent $hookEvent `
            -AgentId $agentId `
            -Decision "block_stop" `
            -Reason $continueReason `
            -Match $matchedPattern `
            -Message $lastMessage `
            -Count $count `
            -ContinuationPrompt $continuationPrompt `
            -GitCommitHash $gitSnapshotHash

        # Output pphoto-style block decision. Current Codex/Claude Stop hooks
        # treat the block reason as the continuation instruction.
        $output = @{{
            decision = "block"
            reason = $continuationPrompt
            suppressOutput = $true
        }} | ConvertTo-Json
        Write-Output $output

    }} finally {{
        # Always remove lock file
        if ($null -ne $lockStream) {{
            try {{
                $lockStream.Dispose()
            }} catch {{
                # Ignore lock stream disposal errors
            }}
        }}
        if (Test-Path $lockPath) {{
            try {{
                Remove-Item -Path $lockPath -Force -ErrorAction SilentlyContinue
            }} catch {{
                # Ignore lock removal errors
            }}
        }}
    }}

}} catch {{
    Write-Log "Unexpected error: $_" "ERROR"
    exit 0  # Allow stop on unexpected error
}}

exit 0
'''

    return script
