"""
Enhanced PowerShell hook script generator with robust error handling.
"""


def generate_hook_script(settings_path: str, enable_git: bool = True) -> str:
    """Generate the PowerShell hook script with enhanced error handling."""
    git_enabled = "$true" if enable_git else "$false"

    script = f'''# Auto-continue hook script
# Generated by API切换器
# Enhanced with robust error handling

$ErrorActionPreference = "Stop"
$gitSnapshotEnabled = {git_enabled}

# Logging function
function Write-Log {{
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logMessage = "$timestamp [$Level] $Message"
    [Console]::Error.WriteLine($logMessage)
}}

# Git快照函数
function Create-GitSnapshot {{
    param([string]$Message = "Auto snapshot before continue")

    try {{
        # 检查是否是git仓库
        $isGitRepo = git rev-parse --git-dir 2>$null
        if (-not $isGitRepo) {{
            # 初始化git仓库
            git init 2>&1 | Out-Null
            Write-Log "Initialized git repository" "INFO"
        }}

        # 检查是否有更改
        $status = git status --porcelain 2>$null
        if ([string]::IsNullOrWhiteSpace($status)) {{
            Write-Log "No changes to commit" "INFO"
            return $true
        }}

        # 添加所有更改
        git add -A 2>&1 | Out-Null

        # 检查git配置
        $userName = git config user.name 2>$null
        $userEmail = git config user.email 2>$null
        if ([string]::IsNullOrWhiteSpace($userName) -or [string]::IsNullOrWhiteSpace($userEmail)) {{
            git config user.name "API-Switcher-Auto" 2>&1 | Out-Null
            git config user.email "auto@api-switcher.local" 2>&1 | Out-Null
            Write-Log "Configured git user" "INFO"
        }}

        # 提交
        $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        $commitMsg = "[$Message] $timestamp"
        git commit -m $commitMsg 2>&1 | Out-Null

        # 获取commit hash
        $commitHash = git rev-parse --short HEAD 2>$null
        Write-Log "Created git snapshot: $commitHash" "INFO"
        return $true

    }} catch {{
        Write-Log "Failed to create git snapshot: $_" "WARN"
        return $false
    }}
}}

try {{
    # Read settings with error handling
    $settingsPath = "{settings_path}"
    if (-not (Test-Path $settingsPath)) {{
        Write-Log "Settings file not found: $settingsPath" "WARN"
        exit 0  # Allow stop if no settings
    }}

    try {{
        $settings = Get-Content $settingsPath -Raw -ErrorAction Stop | ConvertFrom-Json -ErrorAction Stop
    }} catch {{
        Write-Log "Failed to parse settings JSON: $_" "ERROR"
        exit 0  # Allow stop if settings invalid
    }}

    $gitAutoSnapshot = if ($null -eq $settings.PSObject.Properties["git_auto_snapshot"]) {{ $gitSnapshotEnabled }} else {{ [bool]$settings.git_auto_snapshot }}
    $gitSnapshotOnStart = if ($null -eq $settings.PSObject.Properties["git_snapshot_on_start"]) {{ $gitSnapshotEnabled }} else {{ [bool]$settings.git_snapshot_on_start }}

    # Git snapshots are intentionally independent from auto-continue.
    if ($gitAutoSnapshot -and $gitSnapshotOnStart) {{
        Write-Log "Creating git snapshot on stop hook..." "INFO"
        Create-GitSnapshot -Message "git-snapshot"
    }}

    if (-not $settings.enabled) {{
        exit 0  # Allow stop if auto-continue is disabled
    }}

    # Validate settings
    if ($null -eq $settings.max_continuations -or $settings.max_continuations -lt 0) {{
        Write-Log "Invalid max_continuations value" "ERROR"
        exit 0
    }}

    # Read stdin (hook input)
    $stdin = [Console]::In.ReadToEnd()

    if ([string]::IsNullOrWhiteSpace($stdin)) {{
        exit 0  # Allow stop if no input
    }}

    # Parse input JSON with error handling
    try {{
        $hookInput = $stdin | ConvertFrom-Json -ErrorAction Stop
    }} catch {{
        Write-Log "Failed to parse input JSON: $_" "ERROR"
        exit 0
    }}

    # Determine provider based on input structure
    $isClaude = $null -ne $hookInput.hook_event_name
    $isCodex = $null -eq $hookInput.hook_event_name

    # Get session ID and last message
    $sessionId = if ($isClaude) {{ $hookInput.session_id }} else {{ $hookInput.session_id }}
    $lastMessage = if ($isClaude) {{ $hookInput.last_assistant_message }} else {{ $hookInput.last_message }}
    $hookEvent = if ($isClaude) {{ $hookInput.hook_event_name }} else {{ "Stop" }}
    $agentId = if ($isClaude) {{ $hookInput.agent_id }} else {{ $null }}

    if ([string]::IsNullOrWhiteSpace($lastMessage)) {{
        exit 0  # Allow stop if no message
    }}

    # Build state key
    $stateKey = "$sessionId-$hookEvent"
    if ($agentId) {{
        $stateKey = "$stateKey-$agentId"
    }}

    # Load state with file locking
    $stateDir = Split-Path $settingsPath
    $statePath = Join-Path $stateDir "auto_continue_stop_state.json"
    $lockPath = "$statePath.lock"

    # Exclusive file-based locking (wait up to 2 seconds)
    $lockStream = $null
    $lockWait = 0
    while ($null -eq $lockStream -and $lockWait -lt 20) {{
        try {{
            $lockStream = [System.IO.File]::Open(
                $lockPath,
                [System.IO.FileMode]::CreateNew,
                [System.IO.FileAccess]::Write,
                [System.IO.FileShare]::None
            )
        }} catch [System.IO.IOException] {{
            try {{
                if ((Test-Path $lockPath) -and ((Get-Date) - (Get-Item $lockPath).LastWriteTime).TotalSeconds -gt 60) {{
                    Remove-Item -Path $lockPath -Force -ErrorAction SilentlyContinue
                    continue
                }}
            }} catch {{
                # Ignore stale-lock inspection errors and wait.
            }}
            Start-Sleep -Milliseconds 100
            $lockWait++
        }} catch {{
            Write-Log "Failed to create lock file: $_" "WARN"
            exit 0
        }}
    }}

    if ($null -eq $lockStream) {{
        Write-Log "Failed to acquire state file lock" "WARN"
        exit 0  # Allow stop if can't acquire lock
    }}

    try {{
        # Load state
        $state = @{{}}
        if (Test-Path $statePath) {{
            try {{
                $stateContent = Get-Content $statePath -Raw -ErrorAction Stop
                $state = $stateContent | ConvertFrom-Json -ErrorAction Stop -AsHashtable
            }} catch {{
                Write-Log "Failed to parse state JSON, resetting state: $_" "WARN"
                $state = @{{}}
            }}
        }}

        # Get continuation count
        $count = if ($state.ContainsKey($stateKey)) {{ $state[$stateKey] }} else {{ 0 }}

        # Check max continuations
        if ($count -ge $settings.max_continuations) {{
            # Log and allow stop
            $logPath = Join-Path $stateDir "auto_continue_stop_log.jsonl"
            $logEntry = @{{
                timestamp = (Get-Date -Format "o")
                session_id = $sessionId
                hook_event = $hookEvent
                agent_id = $agentId
                decision = "allow_stop"
                reason = "max_continuations_reached"
                count = $count
            }} | ConvertTo-Json -Compress
            try {{
                Add-Content -Path $logPath -Value $logEntry -ErrorAction Stop
            }} catch {{
                Write-Log "Failed to write log: $_" "WARN"
            }}
            exit 0
        }}

        # Check conservative mode for Claude Code
        if ($isClaude -and $settings.conservative_mode -and $hookInput.stop_hook_active) {{
            exit 0  # Allow stop in conservative mode when already continuing
        }}

        # Transient API transport failures should continue even if "error" matches a blocker.
        $recoverableApiErrorPatterns = @(
            "error running remote compact task",
            "stream disconnected before completion",
            "upstream connect error",
            "disconnect/reset before headers",
            "reset reason.*connection termination",
            "error sending request for url",
            "backend-api/codex/responses/compact",
            "responses/compact"
        )
        $isRecoverableApiError = $false
        foreach ($pattern in $recoverableApiErrorPatterns) {{
            try {{
                if ($lastMessage -match $pattern) {{
                    $isRecoverableApiError = $true
                    break
                }}
            }} catch {{
                Write-Log "Invalid recoverable API error pattern: $pattern" "WARN"
            }}
        }}

        # Check blocker patterns with error handling
        $isBlocked = $false
        if ($settings.blocker_patterns) {{
            foreach ($pattern in $settings.blocker_patterns) {{
                try {{
                    if ($lastMessage -match $pattern) {{
                        $isBlocked = $true
                        break
                    }}
                }} catch {{
                    Write-Log "Invalid blocker pattern: $pattern" "WARN"
                }}
            }}
        }}

        if ($isBlocked -and -not $isRecoverableApiError) {{
            exit 0  # Allow stop if blocked
        }}

        # Check incomplete patterns with error handling
        $isIncomplete = $false
        if ($settings.incomplete_patterns) {{
            foreach ($pattern in $settings.incomplete_patterns) {{
                try {{
                    if ($lastMessage -match $pattern) {{
                        $isIncomplete = $true
                        break
                    }}
                }} catch {{
                    Write-Log "Invalid incomplete pattern: $pattern" "WARN"
                }}
            }}
        }}

        if (-not $isIncomplete -and -not $isRecoverableApiError) {{
            exit 0  # Allow stop if complete
        }}

        # Decision: block stop and continue
        $count++
        $state[$stateKey] = $count

        # Save state with atomic write
        try {{
            $tempPath = "$statePath.tmp"
            $state | ConvertTo-Json | Set-Content $tempPath -ErrorAction Stop
            Move-Item -Path $tempPath -Destination $statePath -Force -ErrorAction Stop
        }} catch {{
            Write-Log "Failed to save state: $_" "ERROR"
        }}

        $continueReason = if ($isRecoverableApiError) {{ "recoverable_api_error_detected" }} else {{ "incomplete_work_detected" }}

        # Log decision
        $logPath = Join-Path $stateDir "auto_continue_stop_log.jsonl"
        $logEntry = @{{
            timestamp = (Get-Date -Format "o")
            session_id = $sessionId
            hook_event = $hookEvent
            agent_id = $agentId
            decision = "block_stop"
            reason = $continueReason
            count = $count
            continuation_prompt = $settings.continuation_prompt
        }} | ConvertTo-Json -Compress
        try {{
            Add-Content -Path $logPath -Value $logEntry -ErrorAction Stop
        }} catch {{
            Write-Log "Failed to write log: $_" "WARN"
        }}

        # Output decision
        if ($isClaude) {{
            # Claude Code format
            $output = @{{
                decision = "block"
                reason = $settings.continuation_prompt
                suppressOutput = $true
            }} | ConvertTo-Json
            Write-Output $output
        }} else {{
            # Codex format
            $output = @{{
                continue = $true
                message = $settings.continuation_prompt
            }} | ConvertTo-Json
            Write-Output $output
        }}

    }} finally {{
        # Always remove lock file
        if ($null -ne $lockStream) {{
            try {{
                $lockStream.Dispose()
            }} catch {{
                # Ignore lock stream disposal errors
            }}
        }}
        if (Test-Path $lockPath) {{
            try {{
                Remove-Item -Path $lockPath -Force -ErrorAction SilentlyContinue
            }} catch {{
                # Ignore lock removal errors
            }}
        }}
    }}

}} catch {{
    Write-Log "Unexpected error: $_" "ERROR"
    exit 0  # Allow stop on unexpected error
}}

exit 0
'''

    return script
